apiVersion: v1
data:
  MONGO_INITDB_ROOT_USERNAME: c2VjdXJlLXVzZXJuYW1l
  MONGO_INITDB_ROOT_PASSWORD: c2VjdXJlLXBhc3N3b3Jk
kind: Secret
metadata:
  name: mongodb-secret
  namespace: fullstack-application
type: Opaque
