# Use the official Nginx image from the Docker Hub
FROM nginx:alpine

# Copy the static files to the Nginx web server directory
COPY static /usr/share/nginx/html

# Expose port 80 to allow external traffic to access the web server
EXPOSE 80


