
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-frontend
  namespace: fullstack-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-frontend
  template:
    metadata:
      labels:
        app: nginx-frontend
    spec:
      containers:
      - name: nginx-frontend
        image: maheshchalise/nginx-frontend:v1.0
        ports:
        - containerPort: 80